### PR TITLE
Added Fullbright for more shaders

### PR DESCRIPTION
**Pull request by Hamsteroonie**
Added Fullbright support for particles, block model items, and enchantment glints

### CODE REVIEW

**Comment by Hamsteroonie** [comment]
Also, 1.20.80 broke a lot of shaders, so you need to use 1.20.73 or lower

**Comment by Hamsteroonie** [comment]
Moving blocks still don't work, I'm struggling to figure out which file controls them

**Comment by Hamsteroonie** [comment]
Weather also has issues

**Comment by Furzide** [comment]
I was going to add support for these things myself when I got free time but thanks for contributing, I will review these and I'm pretty sure I can update for latest versions so don't worry abt that

**Comment by Furzide** [comment]
Hey, I have gone ahead and implemented the support for held block models, particles and weather. However I will not be able to implement MeshFallback at this time due to it having a few bugs that I don't know how to fix.
image

**Pull request closed without merging**
